Repository thoughtbot/constable, pull requests merged in 2019-09, with the labels that each got.

#725 Add missing labels to form elements
  lib/constable_web/templates/announcement/_form.html.eex
  lib/constable_web/templates/comment/_form.html.eex
  lib/constable_web/templates/settings/show.html.eex
  lib/constable_web/templates/slack_channel/edit.html.eex
Labels: accessibility, bug

#726 Improve comments area empty state
  assets/css/components/_comments.scss
  lib/constable_web/templates/announcement/show.html.eex
  test/acceptance/new_comment_test.exs
  test/acceptance/user_announcement_test.exs
Labels: improvement

#729 Add Hub integration
  .sample.env
  config/config.exs
  lib/constable/application.ex
  lib/constable/services/hub_profile.ex
  mix.exs
  mix.lock
  test/services/hub_profile_test.exs
Labels: dependencies, elixir, feature

#715 Add Link to Filter by User Having Commented
  lib/constable/models/announcement.ex
  lib/constable_web/controllers/announcement_controller.ex
  lib/constable_web/templates/announcement/index.html.eex
  lib/constable_web/views/announcement_view.ex
  test/controllers/announcement_controller_test.exs
  test/models/announcement_test.exs
Labels: feature

#720 Adds a skip to main content link for screen readers
  lib/constable_web/templates/layout/app.html.eex
Labels: accessibility, feature

#743 Remove gravatar, use Hub profile images
  assets/js/user-autocomplete.js
  assets/static/images/ralph.png
  lib/constable/models/serializers/user.ex
  lib/constable/pact.ex
  lib/constable/services/fake_profile_provider.ex
  lib/constable/services/hub_profile.ex
  lib/constable/services/hub_profile_provider.ex
  lib/constable/services/profile_provider.ex
  lib/constable_web.ex
  lib/constable_web/templates/announcement/_comment.html.eex
  lib/constable_web/templates/announcement/show.html.eex
  lib/constable_web/templates/announcement_list/index.html.eex
  lib/constable_web/templates/email/author_footer.html.eex
  lib/constable_web/templates/email/daily_digest.html.eex
  lib/constable_web/templates/layout/app.html.eex
  lib/constable_web/templates/settings/show.html.eex
  lib/constable_web/templates/user_activation/index.html.eex
  lib/constable_web/views/announcement_view.ex
  lib/constable_web/views/api/user_view.ex
  lib/constable_web/views/email_view.ex
  lib/constable_web/views/shared_view.ex
  mix.exs
  mix.lock
  test/mailers/announcement_mailer_test.exs
  test/mailers/comment_mailer_test.exs
  test/services/hub_profile_test.exs
  test/test_helper.exs
  test/views/api/user_view_test.exs
Labels: elixir, feature

#745 Reduce layout duplication
  lib/constable_web/controllers/session_controller.ex
  lib/constable_web/templates/layout/_content_container.html.eex
  lib/constable_web/templates/layout/_header.html.eex
  lib/constable_web/templates/layout/app.html.eex
  lib/constable_web/templates/layout/login.html.eex
  lib/constable_web/templates/session/_content_container.html.eex
  lib/constable_web/views/announcement_view.ex
  lib/constable_web/views/layout_view.ex
  lib/constable_web/views/shared_view.ex
Labels: chore

#763 Update Inter to v3.10
  assets/static/fonts/Inter-italic.var.woff2
  assets/static/fonts/Inter-upright.var.woff2
Labels: design

#767 Refactor media queries and breakpoints
  assets/css/_shims.scss
  assets/css/app.scss
  assets/css/components/_announcement-create.scss
  assets/css/components/_announcement.scss
  assets/css/components/_app-header.scss
  assets/css/components/_tabs.scss
  assets/css/objects/_container.scss
  assets/css/settings/_grid-settings.scss
  assets/css/settings/_variables.scss
  assets/css/tools/_media.scss
Labels: css

#766 Consistently render Interests as badges
  assets/css/_shims.scss
  assets/css/app.scss
  assets/css/utilities/_font-size.scss
  lib/constable_web/templates/interest/index.html.eex
  lib/constable_web/templates/interest/show.html.eex
  lib/constable_web/templates/slack_channel/edit.html.eex
Labels: css, design
